### ISSUE TITLE
MovingFilter time windows have wrong behavior if not called once-per-step

### ISSUE THREAD

**Issue by possibly-human** [SofaPirate/Plaquette#115]
For objets using a timeWindow (ex: Normalizer, MinMaxScaler...), the timeWindow works according to a rate of 1 update/sampling per step(), and the sampleRate() is not easily modifiable by users.

In certain cases, it would be interesting to be able to set the sample rate.
Ex : I want to normalize a signal with a timeWindow of 5 seconds but sampling the signal at a frequency of 5Hz.

Something like
"normalizer.setSampleRate(5);"
would be ideal.

**Comment by sofian** [comment]
The issue is more complicated to me than simply allowing for unit-specific sample rates, because that still presumes the unit is called once-per-step. In reality, units can be called:
* more than one time per step
* one time ever n-steps
* or even in unpredictable ways due to conditions

To make a robust calculation of the filter, I believe we need to keep the notion of sampleRate() (which just concerns the rate at which step() is called) separated from this issue.

**Comment by sofian** [comment]
When we call ```put(float)``` on the fillter, we could calculate how much time has passed since the last call to ```put(float)``` which would tell us how to adjust based on the target time window. This will work well if we call ```put(float)``` *at most* once per step.

However, if we call several times in one step, there will be no time difference since the last call (cause the step() function is supposed to all happen in a single time step). So I think we'll need to also preserve some kind of average of all values within a single step() to make some kind of an estimate. Not sure how to handle all of this in the most memory-efficient manner.

**Comment by sofian** [comment]
We also have to deal with the isStarted() / _isAdaptive mechanism appropriately.

**Comment by sofian** [comment]
For now I would advise you to precalculate the timeWindow that you need based on sample rate so that we can get things moving. This issue proves to be more complicated than first thought.

**Comment by sofian** [comment]
I implemented a fix for Smoother. @possibly-human can you please put it to test and let me know if it works?

**Comment by possibly-human** [comment]
> I implemented a fix for Smoother. @possibly-human can you please put it to test and let me know if it works?

Will do!

**Comment by possibly-human** [comment]
It works! 
<img width="1415" alt="Capture d’écran, le 2024-06-09 à 14 44 44" src="https://github.com/SofaPirate/Plaquette/assets/168475511/a9257367-bdd0-42e9-9468-4f4059579f09">

**Comment by sofian** [comment]
I implemented fixes for MinMaxScaler and Normalizer but needs testing. @possibly-human

**Comment by possibly-human** [comment]
Seems to work. Not much difference when a normalizer or scaler is called twice in one step. Will keep an eye out for normalizer and scaler behaviour with implemented changes. 

Previous version:
![Previous version](https://github.com/SofaPirate/Plaquette/assets/168475511/ce1bb4b2-c450-497f-a11c-099893fa2b8b)

Updated version:
![Updated](https://github.com/SofaPirate/Plaquette/assets/168475511/4bf11492-bdb7-4732-b3dc-caa07f234928)

Arduino code:
![Code](https://github.com/SofaPirate/Plaquette/assets/168475511/322620b8-59d9-4a38-ba42-964d0350367c)
